FROM python:3

WORKDIR /usr/src/app
COPY requirements.txt ./


RUN apt-get update && apt-get install ca-certificates 
RUN pip3 install --no-cache-dir -r requirements.txt

CMD [ "python", "./pcAgent.py" ]
